### ISSUE TITLE
You haven't submitted your mini ex 7?

### ISSUE THREAD

**Issue by siusoon** [StefanieMik/AP-2017#10]

**Comment by StefanieMik** [comment]
I have been working very hard on it, but I have now had to submit a blank index cause I can't get my code to work.

**Comment by siusoon** [comment]
hey i saw it works...no blank page..

**Comment by siusoon** [comment]
<img width="1002" alt="screen shot 2017-03-27 at 6 24 30 pm" src="https://cloud.githubusercontent.com/assets/1446073/24366817/a56339a2-131a-11e7-8491-ebf008ad01a9.png">
